name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install server dependencies
      run: npm ci
      
    - name: Install client dependencies
      run: cd client && npm ci
      
    - name: Build client
      run: cd client && npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          cd /apps/stafford-dev
          git pull origin main
          npm ci
          cd client && npm ci && npm run build && cd ..
          pm2 restart stafford-dev || pm2 start server.js --name stafford-dev